Use the Activity's context for all Toast notifications
This is an attempt to workaround a crash when showing a toast message.  In limited testing, I haven't been able to reproduce the crash with this patch

I suspect that as the saving of the image is done a separate thread, which had already closed too early causing issues with a non-existent/invalid context

Full crash log:
01-20 11:16:32.599 13130-13130/ca.skilarchhills.android.cameratiming E/AndroidRuntime: FATAL EXCEPTION: main
Process: ca.skilarchhills.android.cameratiming, PID: 13130
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@836917a is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
at android.widget.Toast$TN.handleShow(Toast.java:459)
at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-20 11:16:35.125 13130-13261/ca.skilarchhills.android.cameratiming E/CameraDeviceGLThread-0: Received exception on GL render thread:
    java.lang.IllegalStateException: eglCreateWindowSurface: EGL error: 0x3003
        at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:544)
        at android.hardware.camera2.legacy.SurfaceTextureRenderer.configureEGLOutputSurfaces(SurfaceTextureRenderer.java:466)
        at android.hardware.camera2.legacy.SurfaceTextureRenderer.configureSurfaces(SurfaceTextureRenderer.java:664)
        at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:89)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)